### ISSUE TITLE
File cocycle.py missing

### ISSUE THREAD

**Issue by eric-bunch** [justinlboyer/TDA-CircularValuedParameterfunzation#3]
It looks like in the file circular_valued_parameterization.py it is executing the file cocyle.py through subprocess (e.g. line 75), and it doesn't seem to be present at the moment. Is there something I am missing?

**Comment by justinlboyer** [comment]
I think you might be.  Have you confirmed that dionysus is running, given the tutorial in the readme?  If so then you need to drop a symlink of the cocycle.py file along with any other dependcies in your working directory.  I think you need: cocyle.py, plot.py, and scatter.py

I'm glad you're checking this out! Don't hesitate to ask other questions. What brought you here btw?

**Comment by eric-bunch** [comment]
Ah, I see. I didn't look at the readme close enough. It looks like you're using the first version of Dionysus. I've been using the second version of Dionysus http://mrzv.org/software/dionysus2/  and it looks like the structure of the package is a bit different. 

I'm trying to install Dionysus version 1 at the moment, but am getting an error on the build. Not sure if you have any tips for that, but I will keep playing with it.

I've been looking into how persistent (co)homology can be applied to time series data. I just recently came across the method of circular parametrization, and wondered if there is a good way to use this for time series data. After a quick google search, this repository came up, so I decided to check it out! It seems really interesting from what I can gather from it so far.

One thing I'm not clear on the algorithm that this is employing. I saw the bullet point list in the Jupyter notebook, but was wondering if there was a more detailed explanation of this somewhere?

**Comment by justinlboyer** [comment]
I just checked out Dionysus2, whoa, that would have saved me a lot of time.  Yea since Dionysus 2 is a complete rebuild I'm not sure how integration would go with it.  Installing Dionysus sucks, make sure you have boost and all the dependencies, the install is significantly easier on a linux machine.

**Comment by justinlboyer** [comment]
Honestly fft seems to work really well (better?) than persistent cohomology although persistent cohomology is great from a visualization stand point.  Sorry, I do not have a more detailed explanation, but I'm happy to help.  Contact me on linkedin and I'll pass you my email https://www.linkedin.com/in/justin-l-boyer/.  I'm much faster to respond to email than in this issue.
